"""Protestant 66-book canon and reference aliases."""

from __future__ import annotations

CANON_IDS: tuple[str, ...] = (
    "GEN",
    "EXO",
    "LEV",
    "NUM",
    "DEU",
    "JOS",
    "JDG",
    "RUT",
    "1SA",
    "2SA",
    "1KI",
    "2KI",
    "1CH",
    "2CH",
    "EZR",
    "NEH",
    "EST",
    "JOB",
    "PSA",
    "PRO",
    "ECC",
    "SNG",
    "ISA",
    "JER",
    "LAM",
    "EZK",
    "DAN",
    "HOS",
    "JOL",
    "AMO",
    "OBA",
    "JON",
    "MIC",
    "NAM",
    "HAB",
    "ZEP",
    "HAG",
    "ZEC",
    "MAL",
    "MAT",
    "MRK",
    "LUK",
    "JHN",
    "ACT",
    "ROM",
    "1CO",
    "2CO",
    "GAL",
    "EPH",
    "PHP",
    "COL",
    "1TH",
    "2TH",
    "1TI",
    "2TI",
    "TIT",
    "PHM",
    "HEB",
    "JAS",
    "1PE",
    "2PE",
    "1JN",
    "2JN",
    "3JN",
    "JUD",
    "REV",
)

BOOKS: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ("GEN", "Genesis", ("genesis", "gen", "gn", "ge")),
    ("EXO", "Exodus", ("exodus", "exo", "exod", "ex")),
    ("LEV", "Leviticus", ("leviticus", "lev", "lv")),
    ("NUM", "Numbers", ("numbers", "num", "nu", "nm")),
    ("DEU", "Deuteronomy", ("deuteronomy", "deut", "deu", "dt")),
    ("JOS", "Joshua", ("joshua", "josh", "jos")),
    ("JDG", "Judges", ("judges", "judg", "jdg", "jg")),
    ("RUT", "Ruth", ("ruth", "rut", "ru")),
    ("1SA", "1 Samuel", ("1 samuel", "1samuel", "1 sam", "1sam", "1 sa", "1sa", "1 sm", "1sm")),
    ("2SA", "2 Samuel", ("2 samuel", "2samuel", "2 sam", "2sam", "2 sa", "2sa", "2 sm", "2sm")),
    ("1KI", "1 Kings", ("1 kings", "1kings", "1 kgs", "1kgs", "1 ki", "1ki", "1 k", "1k")),
    ("2KI", "2 Kings", ("2 kings", "2kings", "2 kgs", "2kgs", "2 ki", "2ki", "2 k", "2k")),
    ("1CH", "1 Chronicles", ("1 chronicles", "1chronicles", "1 chr", "1chr", "1 ch", "1ch")),
    ("2CH", "2 Chronicles", ("2 chronicles", "2chronicles", "2 chr", "2chr", "2 ch", "2ch")),
    ("EZR", "Ezra", ("ezra", "ezr")),
    ("NEH", "Nehemiah", ("nehemiah", "neh", "ne")),
    ("EST", "Esther", ("esther", "est", "es")),
    ("JOB", "Job", ("job",)),
    ("PSA", "Psalm", ("psalms", "psalm", "psa", "pss", "ps")),
    ("PRO", "Proverbs", ("proverbs", "proverb", "prov", "prv", "pr")),
    ("ECC", "Ecclesiastes", ("ecclesiastes", "eccles", "eccl", "ecc", "qoh")),
    (
        "SNG",
        "Song of Songs",
        (
            "song of solomon",
            "song of songs",
            "song of sol",
            "canticles",
            "canticle",
            "songs",
            "song",
            "sng",
            "sos",
            "so",
        ),
    ),
    ("ISA", "Isaiah", ("isaiah", "isa")),
    ("JER", "Jeremiah", ("jeremiah", "jer", "je")),
    ("LAM", "Lamentations", ("lamentations", "lamentation", "lam", "la")),
    ("EZK", "Ezekiel", ("ezekiel", "ezek", "eze", "ezk")),
    ("DAN", "Daniel", ("daniel", "dan", "da")),
    ("HOS", "Hosea", ("hosea", "hos", "ho")),
    ("JOL", "Joel", ("joel", "jol", "joe")),
    ("AMO", "Amos", ("amos", "amo", "am")),
    ("OBA", "Obadiah", ("obadiah", "obad", "oba", "ob")),
    ("JON", "Jonah", ("jonah", "jnh", "jon")),
    ("MIC", "Micah", ("micah", "mic")),
    ("NAM", "Nahum", ("nahum", "nam", "nah")),
    ("HAB", "Habakkuk", ("habakkuk", "hab")),
    ("ZEP", "Zephaniah", ("zephaniah", "zeph", "zep", "zp")),
    ("HAG", "Haggai", ("haggai", "hag", "hg")),
    ("ZEC", "Zechariah", ("zechariah", "zech", "zec", "zch")),
    ("MAL", "Malachi", ("malachi", "mal")),
    ("MAT", "Matthew", ("matthew", "matt", "mat", "mt")),
    ("MRK", "Mark", ("mark", "mrk", "mk")),
    ("LUK", "Luke", ("luke", "luk", "lk")),
    ("JHN", "John", ("john", "jhn", "joh", "jn")),
    ("ACT", "Acts", ("acts", "act", "ac")),
    ("ROM", "Romans", ("romans", "roman", "rom", "ro", "rm")),
    ("1CO", "1 Corinthians", ("1 corinthians", "1corinthians", "1 cor", "1cor", "1 co", "1co")),
    ("2CO", "2 Corinthians", ("2 corinthians", "2corinthians", "2 cor", "2cor", "2 co", "2co")),
    ("GAL", "Galatians", ("galatians", "gal", "ga")),
    ("EPH", "Ephesians", ("ephesians", "eph")),
    ("PHP", "Philippians", ("philippians", "philip", "phil", "php")),
    ("COL", "Colossians", ("colossians", "col")),
    ("1TH", "1 Thessalonians", ("1 thessalonians", "1thessalonians", "1 thess", "1thess", "1 th", "1th")),
    ("2TH", "2 Thessalonians", ("2 thessalonians", "2thessalonians", "2 thess", "2thess", "2 th", "2th")),
    ("1TI", "1 Timothy", ("1 timothy", "1timothy", "1 tim", "1tim", "1 ti", "1ti")),
    ("2TI", "2 Timothy", ("2 timothy", "2timothy", "2 tim", "2tim", "2 ti", "2ti")),
    ("TIT", "Titus", ("titus", "tit")),
    ("PHM", "Philemon", ("philemon", "phlm", "phm")),
    ("HEB", "Hebrews", ("hebrews", "heb")),
    ("JAS", "James", ("james", "jas", "jm")),
    ("1PE", "1 Peter", ("1 peter", "1peter", "1 pet", "1pet", "1 pe", "1pe", "1 pt", "1pt")),
    ("2PE", "2 Peter", ("2 peter", "2peter", "2 pet", "2pet", "2 pe", "2pe", "2 pt", "2pt")),
    ("1JN", "1 John", ("1 john", "1john", "1 jhn", "1jhn", "1 jn", "1jn", "1 joh", "1joh")),
    ("2JN", "2 John", ("2 john", "2john", "2 jhn", "2jhn", "2 jn", "2jn", "2 joh", "2joh")),
    ("3JN", "3 John", ("3 john", "3john", "3 jhn", "3jhn", "3 jn", "3jn", "3 joh", "3joh")),
    ("JUD", "Jude", ("jude", "jud")),
    ("REV", "Revelation", ("revelation", "revelations", "rev", "re")),
)

NAMES = {book_id: name for book_id, name, _aliases in BOOKS}
_ALIAS_TO_ID: dict[str, str] = {}
for book_id, name, aliases in BOOKS:
    _ALIAS_TO_ID[name.lower()] = book_id
    _ALIAS_TO_ID[book_id.lower()] = book_id
    for alias in aliases:
        _ALIAS_TO_ID[alias] = book_id

# Longest aliases first so "1 john" wins over "john".
_ALIASES_BY_LENGTH = tuple(sorted(_ALIAS_TO_ID, key=len, reverse=True))


def canon_name(book_id: str) -> str:
    return NAMES[book_id]


def lookup_book(token: str) -> str | None:
    return _ALIAS_TO_ID.get(token)


def aliases_longest_first() -> tuple[str, ...]:
    return _ALIASES_BY_LENGTH
